---
name: Generate sha256 hashes for release files

on:
  push:
    tags:
      - "v*-rev*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- name: Release
      #  uses: softprops/action-gh-release@v1
      - name: Checksums
        uses: wangzuo/action-release-checksums@v1
