---
name: Generate sha256 hashes for release files

on:
  push:
    tags:
      - "v*-rev*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checksums
        uses: wangzuo/action-release-checksums@v1
