---
name: Generate hashes for release files

on:
  push:
    tags:
      - "v*-rev*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          releases-only: true
        id: find-latest-tag
      - name: fetch-gh-release-asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/${{ steps.find-latest-tag.outputs.tag }}'
          regex: true
          file: ".*-msys2\\..*\\.tar\\.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Hashes
        run: |
          ls -R
          for hash_file in `find *.tar.gz -type f -print`; do \
                echo "md5sum	"`md5sum -t $hash_file`         > $hash_file.hash; \
                echo "sha1sum	"`sha1sum -t $hash_file`       >> $hash_file.hash; \
                echo "sha256sum	"`sha256sum -t $hash_file`   >> $hash_file.hash; \
                echo "sha512sum 	"`sha512sum -t $hash_file` >> $hash_file.hash; \
          done

      - name: "💛 Upload hashes to Release"
        id: upload_to_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.find-latest-tag.outputs.tag }}
          #body_path: ${{ github.workspace }}-VERSIONS.txt
          files: |
            *.hash
