---
name: Build toolchains

on:
  push:
    tags:
      - "v*-rev*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: win64-release
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - name: create case sensitive workspace volume for windows
      if: ${{ runner.os == 'Windows' }}
      run: |
        mkdir crosstool-ng
        fsutil file SetCaseSensitiveInfo crosstool-ng enable

    - uses: actions/checkout@v4
      with:
        repository: 'crosstool-ng/crosstool-ng'
        ref: 'master'
        fetch-depth: 0

    - uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: prereq msys2
      if: ${{ runner.os == 'Windows' }}
      run: |
        ls

    - name: Zip artifact for deployment
      run: |
        if ($env:RUNNER_OS -eq "Windows") {
          7z a crosstool-ng-${{ matrix.preset }}.zip install/${{ matrix.preset }}
        } else {
          zip -r crosstool-ng-${{ matrix.preset }}.zip install/${{ matrix.preset }}
        }

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: 'archives'
        path: crosstool-ng-${{ matrix.preset }}.zip


  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: 'archives'
        path: ./
    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload to Release
      id: upload_to_release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.zip"
