---
name: "S2 - Install crosstool"

on:
  workflow_call:
    inputs:
      sample:
        description: Stringified JSON of sample
        required: true
        type: string
      repos:
        description: Stringified JSON of repos
        required: true
        type: string

jobs:
  crosstool:
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        include:
          - { host: "windows-2022", sys: MSYS }
    steps:
      - name: "prereq MSYS2"
        if: ${{ runner.os == 'Windows' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: >-
            base-devel msys2-runtime-devel autotools intltool libtool gcc bison flex gperf help2man meson ninja texinfo patch unzip
            autoconf-archive gettext-devel ncurses-devel
          path-type: inherit
      - name: "prereq Windows"
        if: ${{ runner.os == 'Windows' }}
        run: |
          git config --global core.autocrlf input
          cd ..
          fsutil file SetCaseSensitiveInfo crosstool-ng-msys2-builds enable
          cd crosstool-ng-msys2-builds
      - name: "clone"
        uses: actions/checkout@v4
        with:
          repository: 'crosstool-ng/crosstool-ng'
          ref: 'master'
          fetch-depth: 0
      - name: "build ct-ng"
        shell: msys2 {0}
        run: |
          uname -a
          if [ "$RUNNER_OS" == "macOS" ]; then
            PATH="$PATH:$(brew --prefix)/opt/binutils/bin"
            export PATH
            CPPFLAGS="-I$(brew --prefix)/opt/ncurses/include -I$(brew --prefix)/opt/gettext/include"
            export CPPFLAGS
            LDFLAGS="-L$(brew --prefix)/opt/ncurses/lib -L$(brew --prefix)/opt/gettext/lib"
            export LDFLAGS
          fi
          ./bootstrap
          ./configure --prefix="$PWD/.local/"
          make
          make install
          tar -cf ct-ng.tar .local/
      - name: "upload ct-ng"
        uses: actions/upload-artifact@v4
        with:
          name: crosstool.${{ matrix.host }}
          path: ct-ng.tar
      - name: "upload config.log"
        uses: actions/upload-artifact@v4
        with:
          name: config.log.${{ matrix.host }}
          path: config.log
        if: ${{ always() }}
